---
title: "App Description"
author: "Brad Stieber"
date: "December 30, 2017"
output: html_document
---

# Main Description

Every few weeks or so I do a fairly rudimentary analysis of my personal finances, mainly investigating the balance of my checking account. The typical analysis will look something like:

  1. Read in data
  1. Clean it up a bit
  1. Summarize (visually) in a few different ways
    - Trend in balance
    - Trend in debits / credits
    - Monthly totals
  1. Summarise (numerically) in a few different ways
    - How much have I saved in the last few months
    - How much has my balance grown in the last few months
    - If my savings trends were to continue, how much could I expect to have in 3, 6, or 12 months
      - This requires the fitting of some form of a regression model (a simple linear model seems to do just fine)
      
By now, this analysis has become rather routine, and follows a fairly structured flow. To save myself time (and to re-familiarize myself with git and Shiny), I decided building an automated system might be "fun". 